name: Deploy to GKE
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Authenticate GCloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
      - name: Deploy to GKE
        run: |
          helm upgrade --install cloudcart ./charts/cloudcart